//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogistTr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CargoId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string OrderNumber { get; set; }
        public string Status_ { get; set; }
        public byte[] OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Routes_ Routes_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
