//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogistTr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routes_()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int RouteId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string StartPoint { get; set; }
        public string EndPoint_ { get; set; }
        public Nullable<int> Distance { get; set; }
        public string Status_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
