//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingDetails
    {
        public int SellingDetailID { get; set; }
        public Nullable<int> IDSelling { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> Count_ { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Sellings Sellings { get; set; }
    }
}
