//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sellings()
        {
            this.SellingDetails = new HashSet<SellingDetails>();
        }
    
        public int SellingID { get; set; }
        public Nullable<int> IDCoffeeShop { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> IDSale { get; set; }
    
        public virtual CafeShops CafeShops { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Sales Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellingDetails> SellingDetails { get; set; }
    }
}
